"""empty message

Revision ID: 67835756a51b
Revises: 353476003eba
Create Date: 2025-06-16 20:32:43.637805

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67835756a51b'
down_revision = '353476003eba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task_board_permissions',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('task_board_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['task_board_id'], ['task_boards.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'task_board_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('task_board_permissions')
    # ### end Alembic commands ###
