"""field name added to TaskBoard

Revision ID: 818a9afc5cfe
Revises: b3478ea89f4f
Create Date: 2025-06-15 12:49:13.500958

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '818a9afc5cfe'
down_revision = 'b3478ea89f4f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task_boards', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('name', sa.String(length=120), nullable=False))
        batch_op.create_unique_constraint('uq_task_boards_name', ['name'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task_boards', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('name')

    # ### end Alembic commands ###
